language: csharp
sudo: required
mono: none
dist: xenial
dotnet: 3.0.100
os:
  - linux
  - osx

script:
  - dotnet restore
  - dotnet build -c Release --no-restore --framework netcoreapp3.0 ./src
  - dotnet test  -c Release --no-restore --framework netcoreapp3.0 ./test --filter TestCategory!=IPv6
