version: 2
general:
  branches:
    ignore:
      - gh-pages
jobs:
  dotnet2:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:2.1-sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet build -c Release --framework netstandard2 ./src
      - run: dotnet test --logger "console;verbosity=normal" -c Release --framework netcoreapp2.1 ./test --filter TestCategory!=IPv6
  dotnet3:
    working_directory: /temp
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet build -c Release --framework netcoreapp3.0 ./src
      - run: dotnet test --logger "console;verbosity=normal" -c Release --framework netcoreapp3.0 ./test --filter TestCategory!=IPv6

workflows:
  version: 2
  build-all:
    jobs:
      - dotnet3
      - dotnet2
